### ISSUE TITLE
Assistance Needed with Data Mismatch in Algolia Integration with SFCC (Salesforce commerce cloud)

### ISSUE THREAD

**Issue by VmukundpandeyV** [algolia/algolia-pwa-demo#35]
Hi everyone,

I am experiencing an issue with data mismatch while trying to integrate Algolia with SFCC (Salesforce commerce cloud).

Algolia has provided jobs for product and category indexing, but the attribute formats in which the data is being saved are completely different from those in the PWA composable storefront component. This discrepancy is causing difficulties in consuming the indexed data from Algolia.

Could you please provide a solution for this issue?

Thank you!
V Mukund

**Comment by htuzel** [comment]
Hi @VmukundpandeyV,  

Apologies for the delayed response. Algolia cartridges do offer flexibility in managing which attributes can be indexed. This means you can customize and control the attributes included in the indexing process.  

For detailed guidance, please refer to this [documentation](https://www.algolia.com/doc/integration/salesforce-commerce-cloud-b2c/indexing/product-indexing/indexing-attributes/?client=javascript).  

If there's a specific attribute that we might have overlooked or that you'd like to address, please don’t hesitate to let me know.  

Best
